service: cassava-payment-api
variablesResolutionMode: 20210326
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  apiGateway:
    apiKeys:
      - standardPlan:
          - free-forever-api-key
      - proPlan:
          - pro-api-key
    usagePlan:
      - standardPlan:
          quota:
            limit: 500
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 100
            rateLimit: 50
      - proPlan:
          quota:
            limit: 50000
            offset: 1
            period: MONTH
          throttle:
            burstLimit: 2000
            rateLimit: 1000
package:
  individually: true
plugins:
  - serverless-bundle
  - serverless-offline
functions:
  - ${file(functions/admin/key-management.yml)}
  - ${file(functions/create-apikey/apikey.yml)}
  - ${file(functions/create-invoice/invoice.yml)}
  - ${file(functions/cron/expired-cron.yml)}
  - ${file(functions/cron/reef-cron.yml)}
  - ${file(functions/get-invoice/invoice.yml)}
  - ${file(functions/get-invoices/invoice.yml)}
  - ${file(functions/merchant/merchant-account.yml)}
  - ${file(functions/merchant/merchant-transactions.yml)}

resources:
  - ${file(resources/aws/cognito-user-pool.yml)}
  - ${file(resources/aws/cognito-identity-pool.yml)}
  - ${file(resources/aws/api-gateway-error.yml)}
